# This is a basic workflow to help you get started with Actions

name: Run Test on PR

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the specified branches
  pull_request:
    branches: [ "hw1-f", "hw1-p" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test_sq"
  test_sq:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install pytest
      - name: Install pytest
        run: pip install pytest

      # Run tests
      - name: Run pytest
        run: pytest test_main.py
